WEB_253504_RESHETNEV/Models/ErrorViewModel.cs
namespace WEB_253504_RESHETNEV.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WEB_253504_RESHETNEV/Models/ListDemo.cs
namespace WEB_253504_RESHETNEV.Models;

public class ListDemo
{
    public int Id { get; set; }
    public string Name { get; set; }
}

WEB_253504_RESHETNEV/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using WEB_253504_RESHETNEV.Services.GenreServices;
using WEB_253504_RESHETNEV.Services.BookServices;
using WEB_253504_RESHETNEV.Domain.Entities;
using WEB_253504_RESHETNEV.Domain.Models;

namespace WEB_253504_RESHETNEV.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService _bookService;
        private readonly IGenreService _genreService;

        public BookController(IBookService bookService, IGenreService genreService)
        {
            _bookService = bookService;
            _genreService = genreService;
        }

        public async Task<IActionResult> Index(string? genre, int? page)
        {
            int pageNumber = page ?? 1;
            var genres = await _genreService.GetGenreListAsync();
            var bookResponse = await _bookService.GetBookListAsync(genre, pageNumber);


            if (!bookResponse.Successfull)
                return NotFound(bookResponse.ErrorMessage);

            var currentGenre = genre != "all" ? genres.Data?.Find(g => g.NormalizedName!.Equals(genre))?.Name : "Все";
            ViewData["currentGenre"] = currentGenre;
            ViewData["genres"] = genres.Data;
            ViewData["totalPages"] = bookResponse.Data!.TotalPages;

            return View(new ProductListModel<Book> { Items = bookResponse.Data.Items, CurrentPage = pageNumber, TotalPages = bookResponse.Data.TotalPages });
        }
    }
}

WEB_253504_RESHETNEV/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;

namespace WEB_253504_RESHETNEV.Controllers;

public class CartController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

WEB_253504_RESHETNEV/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WEB_253504_RESHETNEV.Models;

namespace WEB_253504_RESHETNEV.Controllers;

public class HomeController : Controller
{
    [ViewData] public string Text { get; set; } = "Лабораторная работа №3";

    public IActionResult Index()
    {
        var data = new List<ListDemo> { new ListDemo { Id = 1, Name = "Item 1" },
            new ListDemo { Id = 2, Name = "Item 2" },
            new ListDemo { Id = 3, Name = "Item 3"} };
        var list = new SelectList(data, nameof(ListDemo.Id), nameof(ListDemo.Name));

        return View(list);
    }
}

WEB_253504_RESHETNEV/Views/Book/Index.cshtml
@{
ViewBag.Title = "Books";
var request = ViewContext.HttpContext.Request;
var returnUrl = request.Path + request.QueryString.ToUriComponent();
}
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model WEB_253504_RESHETNEV.Domain.Models.ProductListModel<Book>
<div class="col-2 border-2">
    <ul class="nav">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle"
               data-bs-toggle="dropdown"
               href="#"
               role="button"
               aria-expanded="false">
                @ViewData["currentGenre"]
            </a>
            <ul class="dropdown-menu">
                <li>
                    <a class="dropdown-item"
                       asp-controller="Book"
                       asp-route-genre="all"
                       asp-route-page="1">Все</a>
                </li>
                @foreach(var genre in (List<Genre>)ViewData["genres"])
                {
                    <li>
                        <a class="dropdown-item"
                           asp-controller="Book"
                           asp-route-genre="@genre.NormalizedName"
                           asp-route-page="1">
                            @genre.Name
                        </a>
                    </li>
                }
            </ul>
        </li>
    </ul>
</div>

<div class="row">
    @foreach (var item in Model.Items)
    {
    <div class="col-sm-4 mb-4" style="background-color: #000000; display: block">
        <div class="card shadow-sm">
            <div class="card-body d-flex align-items-start" style="height:fit-content">
                <div class="me-3">
                    <img src="@item.ImagePath" alt="No Image" class="img-fluid rounded" style="max-height: 250px; max-width: 200px; margin-bottom: 15px;" />
                    <a asp-controller="Cart" asp-action="Add"
                       asp-route-id="@item.Id"
                       asp-route-returnUrl="@returnUrl"
                       class="btn btn-primary mt-2" style="width: 100%; background-color: #d63384">Добавить в корзину</a>
                </div>
                <div>
                    <h5 class="card-title">@item.Name</h5>
                    <p class="card-text">@item.Description</p>
                </div>
            </div>
        </div>
    </div>
    }
</div>

@{
var currPage = Convert.ToInt32(Context.Request.Query["page"].FirstOrDefault());
var prevPage = currPage == 1 ? 1 : currPage - 1;
var totalPages = Convert.ToInt32(ViewData["totalPages"]);
var nextPage = currPage == totalPages ? totalPages : currPage + 1;
}
<nav aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item" @(currPage == 1 ? "disabled": "")>
            <a class="page-link" aria-label="Previous" asp-route-genre="@(Context.Request.Query["genre"])" asp-route-page="@(prevPage)">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        @{
        for(int i = 0; i < totalPages; i++)
        {
        <li class="page-item @(currPage == i + 1 ? "active" : "")" aria-current="page">
            <a class="page-link" asp-route-genre="@(Context.Request.Query["genre"])" asp-route-page="@(i + 1)">@(i + 1)</a>
        </li>
        }
        }
        <li class="page-item" @(currPage == totalPages ? "disabled": "")>
            <a class="page-link" aria-label="Next" asp-route-genre="@(Context.Request.Query["genre"])" asp-route-page="@(nextPage)">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>

WEB_253504_RESHETNEV/Views/Home/index.cshtml
@{
    ViewBag.Title = "Index";
}


<main class="container mt-5">
    <h1>@ViewData["Text"]</h1>
    <div class="row">
        <div class="col-md-12">
            <h4>Список</h4>
            <ol type="A">
                @{
                    for (int i = 0; i < 5; i++)
                    {
                        <li>Элемент @i списка</li>
                    }
                }
            </ol>
        </div>
        <div class="col-md-12 mt-4">
            <h4>Форма</h4>
            <form method="post">
                <div class="mb-3">
                    <label for="selectList" class="form-label">Выберите элемент:</label>
                    <select id="selectList" name="selectedItemId" class="form-select" asp-items="@Model"></select>
                </div>
                <div class="mb-3">
                    <label class="form-label">Выберите один вариант:</label>
                    <div class="d-flex align-items-center">
                        <div class="form-check me-3">
                            <input type="radio" id="radio1" name="radio" value="1" class="form-check-input">
                            <label for="radio1" class="form-check-label">Радио-1</label>
                        </div>
                        <div class="form-check me-3">
                            <input type="radio" id="radio2" name="radio" value="2" class="form-check-input">
                            <label for="radio2" class="form-check-label">Радио-2</label>
                        </div>
                        <div class="form-check">
                            <input type="radio" id="radio3" name="radio" value="3" class="form-check-input">
                            <label for="radio3" class="form-check-label">Радио-3</label>
                        </div>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="login" class="form-label">Логин:</label>
                    <input type="text" id="login" name="login" class="form-control" placeholder="Введите имя">
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Пароль:</label>
                    <input type="password" id="password" name="password" class="form-control" placeholder="Введите пароль">
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
        </div>
    </div>
</main>

WEB_253504_RESHETNEV/Views/Shared/Components/Cart/Default.cshtml
@{

}
<a asp-controller="Cart" asp-action="Index" class="navbar-text ms-auto">
    00,0 руб <i class="fa-solid fa-cart-shopping"></i> (0)
</a>

WEB_253504_RESHETNEV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="/css/site.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <meta name="viewport" content="width=device-width"/>
    <title>Index</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css"/>
    <link rel="stylesheet" href="~/css/WebLabs_BSUIR_V253504.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <div class="container">
        <!-- Панель навигации -->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <!-- Меню сайта -->
            <partial name="_MenuPartial"/>
            <!-- Меню сайта - конец -->
            <!-- Информация пользователя -->
            
            <partial name="_UserInfoPartial"/>
            
            <!-- Информация пользователя - конец -->
        </nav> <!-- Панель навигации - конец -->
        <span class="nav-color">@* Заголовок страницы *@</span>
    </div>
</header>


@RenderBody()


<footer>
    <div class="icon-container">
        <a class="nav-item nav-link" href="http://www.facebook.com">
            <i class="fa-brands fa-facebook-f fa-2x" style="color: gray;"></i>
        </a>
        <a class="nav-item nav-link" href="http://www.vk.com">
            <i class="fa-brands fa-vk fa-2x" style="color: gray;"></i>
        </a>
        <a class="nav-item nav-link" href="http://www.twitter.com">
            <i class="fa-brands fa-twitter fa-2x" style="color: gray;"></i>
        </a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script async>
    

</script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WEB_253504_RESHETNEV/Views/Shared/_MenuPartial.cshtml
@{
    var controller = ViewContext.RouteData.Values["controller"]?.ToString()?.ToLower() ?? String.Empty;
}

<a asp-controller="Home" asp-action="Index" class="navbar-brand">25350100</a>
<div class="navbar-nav">
    <a asp-controller="Home" asp-action="Index" 
       class="nav-item nav-link @(controller == "home"?"active":"")">Лб 3</a>
    <a asp-controller="Book" asp-action="Index" asp-route-genre="all" asp-route-page="1",
       class="nav-item nav-link @(controller == "movie"?"active":"")">Каталог</a>
    <a asp-area="Admin" asp-page="/Index" 
       class="nav-item nav-link @(controller == "admin"?"active":"")">Администрирование</a>
</div>

WEB_253504_RESHETNEV/Views/Shared/_UserInfoPartial.cshtml
@{
}

@await Component.InvokeAsync("Cart")
<div class="dropdown ms-4 nav-color">
    <button class="btn btn-secondary dropdown-toggle"
            type="button" id="dropdownMenuButton"
            data-bs-toggle="dropdown"
            aria-expanded="false">
        User@gmail.com
        <img src="images/ava.png" width="30" alt="User"
             class="rounded nav-color" />
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <li>
            <span class="dropdown-item-text">
                <img src="images/ava.png" width="50" alt="User" class="rounded" />
                User@gmail.com
            </span>
        </li>
        <li><hr class="dropdown-divider"></li>
        <li>
            <form asp-controller="Account" asp-action="LogOut" id="logoutForm" class="form-inline">
                <button id="logout" type="submit" class="nav-link btn btn-link text-dark">Logout</button>
            </form>
        </li>
    </ul>
</div>